In [1]:
from vizier.datastore.histore.base import HistoreDatastore
TMP_DIR = '../.tmp'

In [2]:
store = HistoreDatastore(TMP_DIR)

In [3]:
from vizier.filestore.base import CSV

ds = store.load_dataset(CSV('../data/etnx-8aft.tsv'), profiler='datamartprofiler')

In [4]:
import json
print(json.dumps(ds.profiling('datamartprofiler'), indent=4))

{
    "nb_rows": 10,
    "nb_profiled_rows": 10,
    "columns": [
        {
            "name": "Calendar Year",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 5,
            "mean": 2016.0,
            "stddev": 1.4142135623730951,
            "coverage": [
                {
                    "range": {
                        "gte": 2014.0,
                        "lte": 2015.0
                    }
                },
                {
                    "range": {
                        "gte": 2016.0,
                        "lte": 2016.0
                    }
                },
                {
                    "range": {
                        "gte": 2017.0,
                        "lte": 2018.0
                    }
                }
            ]
        },
        {
            "name": "Gender",
            "structural_type": "http://schema.org/Text",
            "semantic_types": [],
            "num_distinct_values": 2
        },
        {
            "name": "Physical Abuse",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 10,
            "mean": 79.1,
            "stddev": 14.48067677976413,
            "coverage": [
                {
                    "range": {
                        "gte": 57.0,
                        "lte": 76.0
                    }
                },
                {
                    "range": {
                        "gte": 88.0,
                        "lte": 89.0
                    }
                },
                {
                    "range": {
                        "gte": 98.0,
                        "lte": 105.0
                    }
                }
            ]
        },
        {
            "name": "Sexual Abuse",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 10,
            "mean": 174.3,
            "stddev": 108.94957549251856,
            "coverage": [
                {
                    "range": {
                        "gte": 52.0,
                        "lte": 63.0
                    }
                },
                {
                    "range": {
                        "gte": 95.0,
                        "lte": 95.0
                    }
                },
                {
                    "range": {
                        "gte": 259.0,
                        "lte": 306.0
                    }
                }
            ]
        },
        {
            "name": "Risk of Sexual Abuse",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 9,
            "mean": 63.9,
            "stddev": 30.306599941266914,
            "coverage": [
                {
                    "range": {
                        "gte": 21.0,
                        "lte": 54.0
                    }
                },
                {
                    "range": {
                        "gte": 61.0,
                        "lte": 89.0
                    }
                },
                {
                    "range": {
                        "gte": 134.0,
                        "lte": 134.0
                    }
                }
            ]
        },
        {
            "name": "Risk of Harm",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 9,
            "mean": 227.7,
            "stddev": 33.68694108998322,
            "coverage": [
                {
                    "range": {
                        "gte": 177.0,
                        "lte": 216.0
                    }
                },
                {
                    "range": {
                        "gte": 244.0,
                        "lte": 267.0
                    }
                },
                {
                    "range": {
                        "gte": 293.0,
                        "lte": 293.0
                    }
                }
            ]
        },
        {
            "name": "Emotional/Neglect",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 7,
            "mean": 21.2,
            "stddev": 5.287721626560914,
            "coverage": [
                {
                    "range": {
                        "gte": 14.0,
                        "lte": 18.0
                    }
                },
                {
                    "range": {
                        "gte": 20.0,
                        "lte": 24.0
                    }
                },
                {
                    "range": {
                        "gte": 27.0,
                        "lte": 29.0
                    }
                }
            ]
        }
    ]
}

In [5]:
df = ds.to_dataframe()
df.head()

,Calendar Year,Gender,Physical Abuse,Sexual Abuse,Risk of Sexual Abuse,Risk of Harm,Emotional/Neglect
0,2018,Male,98,60,21,293,29
1,2018,Female,69,306,54,253,29
2,2017,Male,89,62,47,267,17
3,2017,Female,70,286,36,244,18
4,2016,Male,76,52,47,212,17

In [7]:
from openclean import op
from openclean.function import Sum

df = op.inscol(df, 'Abuse Total', pos=4, values=Sum('Physical Abuse', 'Sexual Abuse'))
ds = store.update_dataset(origin=ds, df=df, profiler='datamartprofiler')
df = store.get_dataset(ds.identifier).to_dataframe()
df

,Calendar Year,Gender,Physical Abuse,Sexual Abuse,Abuse Total,Risk of Sexual Abuse,Risk of Harm,Emotional/Neglect
0,2018,Male,98,60,158,21,293,29
1,2018,Female,69,306,375,54,253,29
2,2017,Male,89,62,151,47,267,17
3,2017,Female,70,286,356,36,244,18
4,2016,Male,76,52,128,47,212,17
5,2016,Female,57,259,316,68,216,20
6,2015,Male,105,63,168,61,212,24
7,2015,Female,66,275,341,89,207,27
8,2014,Male,88,95,183,82,196,14
9,2014,Female,73,285,358,134,177,17

In [8]:
print(json.dumps(ds.profiling('datamartprofiler'), indent=4))

{
    "nb_rows": 10,
    "nb_profiled_rows": 10,
    "columns": [
        {
            "name": "Calendar Year",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 5,
            "mean": 2016.0,
            "stddev": 1.4142135623730951,
            "coverage": [
                {
                    "range": {
                        "gte": 2014.0,
                        "lte": 2015.0
                    }
                },
                {
                    "range": {
                        "gte": 2016.0,
                        "lte": 2016.0
                    }
                },
                {
                    "range": {
                        "gte": 2017.0,
                        "lte": 2018.0
                    }
                }
            ]
        },
        {
            "name": "Gender",
            "structural_type": "http://schema.org/Text",
            "semantic_types": [],
            "num_distinct_values": 2
        },
        {
            "name": "Physical Abuse",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 10,
            "mean": 79.1,
            "stddev": 14.48067677976413,
            "coverage": [
                {
                    "range": {
                        "gte": 57.0,
                        "lte": 76.0
                    }
                },
                {
                    "range": {
                        "gte": 88.0,
                        "lte": 89.0
                    }
                },
                {
                    "range": {
                        "gte": 98.0,
                        "lte": 105.0
                    }
                }
            ]
        },
        {
            "name": "Sexual Abuse",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 10,
            "mean": 174.3,
            "stddev": 108.94957549251856,
            "coverage": [
                {
                    "range": {
                        "gte": 52.0,
                        "lte": 63.0
                    }
                },
                {
                    "range": {
                        "gte": 95.0,
                        "lte": 95.0
                    }
                },
                {
                    "range": {
                        "gte": 259.0,
                        "lte": 306.0
                    }
                }
            ]
        },
        {
            "name": "Abuse Total",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 10,
            "mean": 253.4,
            "stddev": 97.67722354776471,
            "coverage": [
                {
                    "range": {
                        "gte": 128.0,
                        "lte": 183.0
                    }
                },
                {
                    "range": {
                        "gte": 316.0,
                        "lte": 341.0
                    }
                },
                {
                    "range": {
                        "gte": 356.0,
                        "lte": 375.0
                    }
                }
            ]
        },
        {
            "name": "Risk of Sexual Abuse",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 9,
            "mean": 63.9,
            "stddev": 30.306599941266914,
            "coverage": [
                {
                    "range": {
                        "gte": 21.0,
                        "lte": 54.0
                    }
                },
                {
                    "range": {
                        "gte": 61.0,
                        "lte": 89.0
                    }
                },
                {
                    "range": {
                        "gte": 134.0,
                        "lte": 134.0
                    }
                }
            ]
        },
        {
            "name": "Risk of Harm",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 9,
            "mean": 227.7,
            "stddev": 33.68694108998322,
            "coverage": [
                {
                    "range": {
                        "gte": 177.0,
                        "lte": 216.0
                    }
                },
                {
                    "range": {
                        "gte": 244.0,
                        "lte": 267.0
                    }
                },
                {
                    "range": {
                        "gte": 293.0,
                        "lte": 293.0
                    }
                }
            ]
        },
        {
            "name": "Emotional/Neglect",
            "structural_type": "http://schema.org/Integer",
            "semantic_types": [],
            "unclean_values_ratio": 0.0,
            "num_distinct_values": 7,
            "mean": 21.2,
            "stddev": 5.287721626560914,
            "coverage": [
                {
                    "range": {
                        "gte": 14.0,
                        "lte": 18.0
                    }
                },
                {
                    "range": {
                        "gte": 20.0,
                        "lte": 24.0
                    }
                },
                {
                    "range": {
                        "gte": 27.0,
                        "lte": 29.0
                    }
                }
            ]
        }
    ]
}

In [9]:
# Clean up the temp directory
import shutil

shutil.rmtree(TMP_DIR)